# Generated by Django 2.0.3 on 2018-04-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_auto_20180414_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('firstCRM_table_list', '可以查看kingadmin每张表里所有的数据'), ('firstCRM_table_list_view', '可以访问kingadmin表里每条数据的修改页'), ('firstCRM_table_list_change', '可以对kingadmin表里的每条数据进行修改'), ('firstCRM_table_obj_add', '可以对kingadmin每张表进行数据添加'))},
        ),
    ]
