# Generated by Django 2.0.3 on 2018-04-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstCRM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menus',
        ),
        migrations.RemoveField(
            model_name='role',
            name='menus',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
